// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddAlertsResponse AddAlertsResponse
//
// swagger:model AddAlertsResponse
type AddAlertsResponse struct {

	// alert id
	AlertID string `json:"alert_id,omitempty"`
}

// Validate validates this add alerts response
func (m *AddAlertsResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddAlertsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddAlertsResponse) UnmarshalBinary(b []byte) error {
	var res AddAlertsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
